import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  // Generated, vendored, or non-source output — never lint these.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      ".remember/**",
      "app/.well-known/**", // generated by withWorkflow at build time
      "lib/generated/**",
      "prisma/generated/**",
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // The agent core (agent/*) and the Google Identity Services / Calendar
    // bindings (lib/google/*) are created verbatim from LOGIC_SNIPPETS.md
    // (CLAUDE.md §5 — do not rewrite the loop/tools). Their `any`s sit at
    // genuinely untyped SDK boundaries: the Gemini `contents` array, the GIS
    // `google` global, and the model's dynamic tool-argument bags. Relax the
    // explicit-any rule there only; the rest of the app stays strict.
    files: ["agent/**/*.ts", "lib/google/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];

export default eslintConfig;
